### ISSUE TITLE
Update Anthropic Client 

### ISSUE THREAD

**Issue by ghost** [bcdnlp/PRD#1]
Anthropic changed their python sdk - making this code line outdated.

https://github.com/bcdnlp/PRD/blob/fcc27342305fffe7b8dcb420f5d30bb7383406e7/peer_discussion/anthropic_api.py#L26

---

Would love to know if this might help - https://github.com/BerriAI/litellm

~Simple I/O library, that standardizes all the llm api calls to the OpenAI call

```
from litellm import completion

## set ENV variables
# ENV variables can be set in .env file, too. Example in .env.example
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["ANTHROPIC_API_KEY"] = "anthropic key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# anthropic call
response = completion("claude-v-2", messages)

```

**Comment by ghost** [comment]
cc: @NekoMimiUnagi

**Comment by NekoMimiUnagi** [comment]
Thank you for mentioning it. I'll update the code first. That library may help. I'll update it later.
